[project]
name = "hshmeng"
version = "2024.10.22.1"
authors = [{ name="hshmeng", email="hshmeng@foxmail.com" }, ]
description = "You hshmeng ZhiZuoDeZhongWenBianChengBao"
readme = "README.md"
requires-python = ">=3.8"